services:
  db:
    image: postgres:13
    container_name: homeassistant-postgres
    volumes:
      - ./config_postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgresadmin
      - POSTGRES_PASSWORD=${HOMEASSISTANT_PG_PASSWORD}
      - POSTGRES_DB=homeassistant
    restart: unless-stopped
    network_mode: host

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config_homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    ports:
      - 8123:8123
    depends_on:
      - mosquitto
    restart: unless-stopped
    privileged: true
    network_mode: host

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "1883:1883/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config_mosquitto/config:/mosquitto/config
      - ./config_mosquitto/data:/mosquitto/data
      - ./config_mosquitto/log:/mosquitto/log
    network_mode: host
    stdin_open: true
    tty: true

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    ports:
      - "8099:8099/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config_zigbee2mqtt/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_baf0b5bdd7e7ed11b34cd6770b2af5ab-if00-port0:/dev/ttyACM0
    network_mode: host
